### ISSUE TITLE
Steps preceding a 'switch' execute multiple times

### ISSUE THREAD

**Issue by mitel** [ash-project/reactor#132]
**Describe the bug**
Steps preceding a `switch` execute multiple times. The code below will output 'MOO' and 'BOO' twice. 
(It only happens if those steps do not halt). 
The debug step also executes twice, not sure if that is ok.

**To Reproduce**

Reactor.run(SwitchReactor, %{value: true})

```
defmodule SwitchReactor do
  @moduledoc false
  use Reactor

  input :value

  debug :debug do
    argument :value, input(:value)
  end

  step :moo do
    argument :value, input(:value)

    run fn %{value: value}, _ ->
      IO.puts IO.ANSI.format([:yellow_background, :black, "MOOO"])

      {:ok, value}
    end
  end

  step :boo do
    argument :value, input(:value)

    wait_for :moo

    run fn %{value: value}, _ ->
      IO.puts IO.ANSI.format([:yellow_background, :black, "BOOO"])

      {:ok, !value}
    end
  end

  switch :is_truthy? do
    on result(:boo)

    matches? &(&1 in [nil, false]) do
      # step :falsy, Noop

      step :falsy do
        argument :value, input(:value)

        wait_for :boo

        run fn %{value: value}, _ ->
          IO.puts IO.ANSI.format([:yellow_background, :black, "falsy"])

          {:ok, value}
        end
      end

      return :falsy
    end

    default do
      step :truthy, Noop

      return :truthy
    end
  end

  return :is_truthy?
end
```

**Expected behavior**
The steps should be executed only once.

**Runtime**
 - Elixir version: 1.16.3
 - Erlang version: 26
 - OS: ubuntu-focal-20231003
 - Spark version: 2.2.35
 - reactor 0.10.0

**Comment by zachdaniel** [comment]
Definitely not desired at all. @jimsynz you have a chance to look into this?

**Comment by mitel** [comment]
@jimsynz thank you for the fix! @zachdaniel would love to have this to migrate my flows to reactors. thx!!
